#!/bin/bash


set -ex


dockerRepo="${DOCKER_REPO}"
currentTag="${DOCKER_TAG}"
features=`echo "${currentTag}" | sed -e 's/.*--\(\)/\1/'`

imageName='Base docker image for PHP applications'
imageDescription='Alpine based docker image with Apache (prefork) & PHP module.'
imageVersion="${currentTag}"
vcsUrl='https://github.com/prog/docker-php'
vcsRef=`git rev-parse --short HEAD`
buildDate=`date -u +'%Y-%m-%dT%H:%M:%SZ'`


case "${features}" in
	'php7.1-apache2.4-alpine3.6')
		phpPackage='php7-apache2<7.1.999'
		;;
	'php5.6-apache2.4-alpine3.6')
		phpPackage='php5-apache2<5.6.999'
		;;
	*)
		(>&2 echo "ERROR: invalid tag: '${currentTag}'")
		exit 1
		;;
esac


docker build \
	--build-arg "PHP_PACKAGE=${phpPackage}" \
	--label "org.label-schema.name=${imageName}" \
	--label "org.label-schema.description=${imageDescription}" \
	--label "org.label-schema.version=${imageVersion}" \
	--label "org.label-schema.vcs-url=${vcsUrl}" \
	--label "org.label-schema.vcs-ref=${vcsRef}" \
	--label "org.label-schema.build-date=${buildDate}" \
	--label "org.label-schema.schema-version=1.0" \
	-t "${dockerRepo}:${currentTag}" .
